version: '3.3'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  springapp:
    build:
      context: .
      dockerfile: cache-manager/Dockerfile
    container_name: springapp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mock
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/test?authSource=admin
      TOKEN_SERVICE_URL: http://mock:8080/teste  # Configura a URL do mock como variável de ambiente
    volumes:
      - ./logs:/app/logs

  mock:
    build:
      context: .
      dockerfile: mock/Dockerfile 
    container_name: mock
    ports:
      - "8081:8080"  
      
volumes:
  mongo-data:
